# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, pkgs, lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelModules = [ "kvm-amd" "k10temp" ];
  boot.blacklistedKernelModules = [ "usblp" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/3ec06060-b113-4b3f-b5e4-ad21156c9f0a";
      fsType = "btrfs";
    };

  fileSystems."/boot/efi" =
    {
      device = "/dev/disk/by-uuid/FE79-50CE";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/1a34efa0-d48f-4a53-b52f-6334c01a53c2";
      fsType = "btrfs";
    };

  fileSystems."/disks/wd_blue" =
    {
      device = "/dev/disk/by-uuid/828c72af-2634-4eea-a9c4-4320f2c8878c";
      fsType = "btrfs";
      options = [ "subvolid=5" "noatime" ];
    };

  fileSystems."/disks/wd_blue/games" =
    {
      device = "/dev/disk/by-uuid/828c72af-2634-4eea-a9c4-4320f2c8878c";
      fsType = "btrfs";
      options = [ "subvol=games" "compress=zstd:3" "noatime" ];
    };

  fileSystems."/disks/wd_blue/video" =
    {
      device = "/dev/disk/by-uuid/828c72af-2634-4eea-a9c4-4320f2c8878c";
      fsType = "btrfs";
      options = [ "subvol=video" "nodatacow" "noatime" ];
    };

  swapDevices = [{
    device = "/var/lib/swapfile";
    size = 20 * 1024;
  }];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.enableRedistributableFirmware = true;
  hardware.enableAllFirmware = true;
}
