[outputs.main]
name = "eDP-1"
width = "1920"
height = "1080"
framerate = "120"
scale = "1"
transform = "normal"
offset = { x = "0", y = "0" }

[outputs.secondary]
name = "HDMI-A-1"
width = "1920"
height = "1080"
framerate = "60"
scale = "1"
transform = "normal"
offset = { x = "-1920", y = "0" }
